### ISSUE TITLE
GeoMap: scrolling on trackpad extremely buggy

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#116]
##### Geo version

0.2.8

##### Orange version

3.28.dev

##### Expected behavior
Zooming is smooth and very granular (allows very fine changes between zoom levels).

##### Actual behavior
Zooming is very patchy on trackpad (Macbook PRO). There are few 'levels' of zoom. Even selecting a zoom region doesn't correspond to the selected region, but the region+some extra territory.

##### Steps to reproduce the behavior
Zoom with trackpad.

##### Additional info (worksheets, data, screenshots, ...)
/

**Comment by robertcv** [comment]
There are normally around 16 levels of zoom depending on the map you are using. We can't show more as there is nothing more to show (web-based libraries work on the same images). You would probably like to have smoother transitions between levels. This was not implemented as we thought it would impact performance. For the best visuals it is important to match displayed maps resolution with widget display resolution. That's whay the select region is not exact. The widget finds the closes but bigger region where resolutions match.

**Comment by robertcv** [comment]
I was just able to observe the zoom problem on a friend's mac. Although I don't have the means to debug the problem myself I am pretty sure the cause of the problem is that the mac's touchpad doesn't call the `wheelEvent` (or the parameters are something unexpected) that is overridden in [plotutils.py](https://github.com/biolab/orange3-geo/blob/ba4b7b6d84b3ce87236c6a68fb0992fcd5da3b07/orangecontrib/geo/widgets/plotutils.py#L122) that then actually calls appropriate functions to update the background for different zoom levels.
