### ISSUE TITLE
Version 3 with only 1 widget

### ISSUE THREAD

**Issue by jaherrerarodriguez** [biolab/orange3-geo#124]
I installed version 3 of the addon a few minutes ago and it does not include the Chloropletic and GeoCoding map widgets.

##### Geo version
3.0

##### Orange version
3.28

**Comment by PrimozGodec** [comment]
We just released Orange3-geo and since the Conda package was not built yet you passed on PyPI package. There is a known issue with the `shapely` library that we are using in the add-on when installing with PyPI https://github.com/Toblerity/Shapely/issues/1105. It will go away in version 2.0. 👍 

Since now Conda build for geo addon is ready, you can try to reinstall Orange3-geo, but the problem here is that you also need to manually remove Shapely. So please go to the folder where Orange is installed. By default, it should be C:\Users\<your usernam>\AppData\Local\Programs\Orange and open `Orange command prompt`. There type `pip uninstall orange3-geo shapely` when it is successfully uninstalled open Orange and install Orange3-geo again from the addon dialog. If you need any further assistance please let me know.
